### ISSUE TITLE
How to display your results ?

### ISSUE THREAD

**Issue by snblg** [wongm/zenphoto-on-this-day#1]
Hello,

What should I add in my Zenphoto theme to be able to use your php extension ?
Thanks in advance.

**Comment by wongm** [comment]
One example is here - creating a RSS feed item for a given day.

https://railgallery.wongm.com/page/rss-on-this-day

The code that drives it is here:

https://github.com/wongm/wongm-rail-gallery-theme/blob/master/rss-on-this-day.php

A second example is a "On this day" page in HTML:

https://railgallery.wongm.com

The code that drives that instance is here:

https://github.com/wongm/wongm-rail-gallery-theme/blob/master/index.php

**Comment by wongm** [comment]
I've since updated the readme file to describe how the plugin works, list available data fields, and include a sample theme file so you can get it working quickly
